### ISSUE TITLE
Test fail.

### ISSUE THREAD

**Issue by XoneFobic** [brianwebb01/hexagonal-laravel-experiment#2]
I like this concept of doing things.
So I've been recreating it (Learn better when typing it out).

But once I hit the tests it seem to fail.
First on missing dependencies (mockery and factory from jeffrey), so added them to the composer.json file.

But now I get `
Fatal error: Class 'Eloquent' not found in /var/www/tests/hexagonal-laravel-experiment/app/models/Order.php on line 5`

I'm guessing it's the `$this->mock = m::mock('Eloquent', 'Order');` in the `OrdersTest.php` file.
But as I'm pretty new to TDD; I figured to say it here before I started tinkering.

Also added a travis-ci file, but that's irrelevant still.
[![Build Status](https://travis-ci.org/XoneFobic/hexagonal-laravel-experiment.png?branch=master)](https://travis-ci.org/XoneFobic/hexagonal-laravel-experiment) https://travis-ci.org/XoneFobic/hexagonal-laravel-experiment

Even with the test failing. Nice work so far, I'll see if I can implement it in my current project

**Comment by brianwebb01** [comment]
The app is just something quick that is thrown together, any tests that might be included may have been generated as part of the scaffold command from way\generators.  That said I never shipped it with passing tests.

It should just work if you create a new DB, run the migrations and go.
